# 종이에 나와있는 문제와 수업 포함

USE sqlDB;



SELECT USERID, NAME FROM userTBL WHERE birthYear<1970 AND height <180; # 1번
SELECT USERID, NAME FROM userTBL WHERE birthYear<1970 OR height <180;

SELECT USERID, NAME FROM USERTBL WHERE HEIGHT >= 180 AND HEIGHT <= 183;
SELECT USERID, NAME FROM USERTBL WHERE HEIGHT BETWEEN 180 AND 183;

SELECT USERID, NAME FROM USERTBL WHERE ADDR= '서울' AND birthYear>1980; # 2번

SELECT USERID FROM buytbl WHERE productName = '운동화' OR productName = '모니터'; # 3번

SELECT NAME, ADDR FROM USERTBL WHERE ADDR = '전남' OR ADDR = '경북' OR ADDR = '경남';
SELECT NAME, ADDR FROM USERTBL WHERE ADDR IN ('전남', '경북', '경남');
SELECT NAME, ADDR FROM USERTBL WHERE ADDR = '전남' OR '경북' OR '경남'; # ADDR = '전남'까지만 인식 -> 틀린 코드

SELECT NAME,height FROM USERTBL WHERE NAME LIKE '김%'; #LIKE -> 특정 조건을 가진 문자를 찾아준다. %는 그 방향에는 무엇이 붙든 상관이 없다는 의미
SELECT NAME, HEIGHT FROM USERTBL WHERE NAME LIKE '_종신'; #_는 한 글자 아무거나 상관없다는 의미?
SELECT USERID, NAME FROM USERTBL WHERE NAME LIKE '%용%'; # %는 _로 대체 가능, 4번

SELECT HEIGHT FROM USERTBL WHERE NAME = '김경호';
SELECT NAME, HEIGHT FROM USERTBL WHERE HEIGHT >177;
SELECT NAME, HEIGHT FROM USERTBL 
	WHERE HEIGHT > (SELECT HEIGHT FROM USERTBL WHERE NAME = '김경호'); #서브쿼리 사용 -> 여러 문장을 합칠 수 있다.
SELECT USERID, HEIGHT FROM USERTBL
	WHERE HEIGHT < (SELECT HEIGHT FROM USERTBL WHERE ADDR = '서울'); #5번 #REGION이 서울인 사람이 여러명이므로 HEIGHT VALUE가 여러 개 -> 누구 키보다 작은데?
SELECT NAME, HEIGHT FROM USERTBL
	WHERE HEIGHT < ANY(SELECT HEIGHT FROM USERTBL WHERE ADDR = '서울'); #5번 솔루션 -> ANY를 붙인다 -> 결과값을 모두 부등호 돌려보고 각자보다 작은 케이스를 모두 고려, IN 또는 OR과 비슷하다고 보면 됨alter
    
SELECT NAME, MDATE FROM USERTBL ORDER BY MDATE;  # ORDER BY -> SORTING, 이 경우는 MDATE를 기준으로 정렬, 기본은 오름차순.
SELECT NAME, MDATE FROM USERTBL ORDER BY MDATE DESC; #DESC : DESCENDING, 내림차순으로 정렬
SELECT NAME, MDATE FROM USERTBL ORDER BY MDATE ASC; #내림차순한 것을 다시 오름차순으로 정렬
SELECT USERID, NAME, HEIGHT FROM USERTBL ORDER BY HEIGHT DESC; #6번 중간, 아이디 겹칠 경우는?
SELECT USERID, NAME, HEIGHT FROM USERTBL ORDER BY HEIGHT DESC, USERID ASC; #6번 솔루션, 그냥 뒤에 붙여주면 됨
SELECT USERID, NAME, HEIGHT FROM USERTBL ORDER BY HEIGHT DESC, USERID DESC;#위 문장과 차이가 보일 것이다

SELECT ADDR FROM USERTBL; #겹친 부분도 모두 나온다.
SELECT ADDR FROM USERTBL ORDER BY ADDR;#정렬되었지만 여전히 중복되는 부분이 있다.
SELECT distinct ADDR FROM USERTBL ORDER BY ADDR; #필드 이름 앞에 DISTINCT를 붙이니 중복된 부분이 삭제
SELECT DISTINCT productName, PRICE FROM BUYTBL ORDER BY PRICE DESC; #7번

USE EMPLOYEES; #8번, 새로운 스키마(DB)를 선택
SELECT EMP_NO, FIRST_NAME, HIRE_DATE FROM employees ORDER BY HIRE_DATE; # 고용 날짜를 오름차순(오래된 순서)로 정렬
SELECT EMP_NO, FIRST_NAME, HIRE_DATE FROM employees ORDER BY HIRE_DATE;


#TABLE COPY
USE SQLDB;
CREATE TABLE BUYTBL2(SELECT * FROM BUYTBL); 
